name = "room-spa"
account_id = "c7df347268e6c5bda755bdb802428ca8"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-07-25"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_GA_MEASUREMENT_ID = "G-D2NJJ1ZPF5"

[assets]
directory = "./dist/client"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "none"
run_worker_first = ["/videos/*"]
